apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: rw
  labels:
    name: resource-watch-preproduction
  name: resource-watch-preproduction
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: resource-watch-preproduction
    spec:
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "webapps"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - resource-watch-preproduction
                topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: regcred
      containers:
        - name: resource-watch-preproduction
          image: vizzuality/resource-watch
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_SECRET
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
            - name: RW_GOGGLE_API_TOKEN_SHORTENER
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_GOGGLE_API_TOKEN_SHORTENER
            - name: RW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_PREPROD_AUTH_USER
            - name: RW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_PREPROD_AUTH_PASSWORD

          ports:
            - containerPort: 3000
      restartPolicy: Always
