apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: rw
  labels:
    name: resource-watch-staging
  name: resource-watch-staging
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: resource-watch-staging
    spec:
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "webapps"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - resource-watch-staging
                topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: regcred
      containers:
        - name: resource-watch-staging
          image: vizzuality/resource-watch
          imagePullPolicy: Always
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_SECRET
            - name: RW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_STAGING_AUTH_USER
            - name: RW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_STAGING_AUTH_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
            - name: RW_GOGGLE_API_TOKEN_SHORTENER
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_GOGGLE_API_TOKEN_SHORTENER
          ports:
            - containerPort: 3000
      restartPolicy: Always
